version: "2.1"

services:
  mysql:
    image: mysql:8.0.32
    mem_limit: 512m
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: QUESTIONDB_DDD_AXON
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    healthcheck:
      test: "/usr/bin/mysql --user=user --password=pwd --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 60
    # volumes:
      # - ./dump-scripts:/docker-entrypoint-initdb.d

  axonserver:
    image: axoniq/axonserver
    ports:
      - 8024:8024
      - 8124:8124


