spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
server.error.include-message: always

spring.datasource:
  url: jdbc:mysql://localhost:3307/image-upload-api-db
  username: user
  password: pwd